name: build catime

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'README_EN.md'
      - 'SECURITY.md'
      - 'PRIVACY.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'README_EN.md'
      - 'SECURITY.md'
      - 'PRIVACY.md'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      artifact-id: ${{ steps.upload-unsigned.outputs.artifact-id }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up China timezone
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        echo "Current timezone: $(date +%Z)"
        echo "Current time: $(date)"
        
    - name: Install MinGW compiler and CMake
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64 cmake
        cmake --version
        
    - name: Extract version number
      id: get_version
      run: |
        VERSION=$(grep -oP '#define CATIME_VERSION "\K[^"]+' resource/resource.h)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"
      
    - name: Build application
      run: |
        # Create output directory
        mkdir -p output
        
        # Run the build script which handles CMake configuration and compilation
        chmod +x build.sh
        ./build.sh
        
        # Copy the build artifact to output directory
        cp build/catime.exe output/
        echo "Build completed using CMake"
        
    - name: Rename output file
      run: |
        # Rename to versioned filename
        mv output/catime.exe output/catime_${{ env.VERSION }}_${{ github.run_number }}.exe
        
    - name: Upload build artifacts
      id: upload-unsigned
      uses: actions/upload-artifact@v4
      with:
        name: catime-windows-${{ env.VERSION }}-${{ github.run_number }}
        path: output/catime_${{ env.VERSION }}_${{ github.run_number }}.exe

  # Code signing job - only execute on main branch commits
  sign:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    uses: ./.github/workflows/signpath-sign.yml
    with:
      artifact-name: catime-windows-${{ needs.build.outputs.version }}-${{ github.run_number }}
      artifact-id: ${{ needs.build.outputs.artifact-id }}
      version: ${{ needs.build.outputs.version }}
      is-release: false
    secrets:
      SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}

  # Clean up temporary artifacts
  cleanup:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: sign
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - name: Delete temporary signing package
      uses: geekyeggo/delete-artifact@v4
      with:
        name: catime-signing-package
        failOnError: false